name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Install Dependencies
        run: npm i

      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Build
        run: make build
