name: Publish
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: siacentral/sia-lite-wallet-web:latest
      - name: ghcr
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: SIACENTRAL_TOKEN=${{ secrets.WALLET_AUTH_TOKEN }}
          push: true
          tags: ghcr.io/siacentral/sia-lite-wallet-web:latest
  skynet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Build
        run: |
          export VUE_APP_VERSION=$(git rev-parse --short HEAD)
          make build
      - name: Deploy
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dist
          registry-seed: ${{ secrets.SKYWALLET_SKYDB_SEED }}